- name: Install Nginx Web Server on Ubuntu Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx systemd
- name: Replace nginx_default
  template:
    src=templates/default
    dest=/etc/nginx/sites-enabled/default
  notify: Restart nginx